name: totalpay_checkout_sdk
description: A Flutter SDK for TotalPay checkout integration.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  crypto: ^3.0.3
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.8.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
